[package]
name = "loom"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]

[dependencies]
unicode_categories = "0.1.0"
unicode-segmentation = "0.1.2"
nom = "1.2.0"
daggy = "0.3.0"
# power-assert = "0.3.5"
