[package]
name = "loom"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]

[dependencies]
unicode_categories = "*"
unicode-brackets = "*"
rusttype = "*"
roman = "*"
fst = "*"
rmp = "*"
rmp-serialize = "*"
rustc-serialize = "*"
lz4 = "*"
broadcast = "*"
mio = "*"
clap = {version="*", features=["yaml"]}
derivative = "*"
itertools = "*"
futures = "*"
curl = "*"

[dependencies.image]
default-features = false
features = ["png_codec"]
version = "0.10.3"

[dependencies.nom]
#git = "https://github.com/Geal/nom.git"
git = "https://github.com/s3bk/nom.git"
#path = "../nom"
default_features = false
features = ["slug"]
#version = "0.4"

[dependencies.woot]
git = "https://github.com/s3bk/woot.git"
#path = "../woot"

[[bin]]
name = "render_image"

[[bin]]
name = "hyphen_import"

[[bin]]
name = "profile_parser"
