layout([
  [0, "Chapter"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "Ref-"],
  [1, false],
  [0, "erence"],
  [4, 3],
  [0, "Refer-"],
  [1, false],
  [0, "ence"],
  [4, 1],
  [0, "Reference"],
  [1, true],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "big"],
  [2, true, 1],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "small"],
  [2, true, 1],
  [0, "A"],
  [2, true, 1],
  [0, "yarn"],
  [2, true, 1],
  [0, "is"],
  [2, true, 1],
  [0, "an"],
  [2, true, 1],
  [3, 4],
  [0, "or-"],
  [1, false],
  [0, "dered"],
  [4, 1],
  [0, "ordered"],
  [2, true, 1],
  [3, 4],
  [0, "se-"],
  [1, false],
  [0, "quence"],
  [4, 1],
  [0, "sequence"],
  [2, true, 1],
  [0, "of"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "En-"],
  [1, false],
  [0, "tities"],
  [4, 3],
  [0, "Enti-"],
  [1, false],
  [0, "ties"],
  [4, 1],
  [0, "Entities"],
  [2, true, 1],
  [0, "occurring"],
  [2, true, 1],
  [0, "in"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "Doc-"],
  [1, false],
  [0, "ument"],
  [4, 3],
  [0, "Docu-"],
  [1, false],
  [0, "ment"],
  [4, 1],
  [0, "Document"],
  [0, "."],
  [1, true],
  [0, "In"],
  [2, true, 1],
  [0, "most"],
  [2, true, 1],
  [3, 4],
  [0, "cas-"],
  [1, false],
  [0, "es"],
  [4, 1],
  [0, "cases"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [0, "main"],
  [2, true, 1],
  [0, "yarn"],
  [2, true, 1],
  [0, "is"],
  [2, true, 1],
  [0, "build"],
  [2, true, 1],
  [0, "from"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [3, 4],
  [0, "text-"],
  [1, false],
  [0, "body"],
  [4, 1],
  [0, "textbody"],
  [2, true, 1],
  [0, "which"],
  [2, true, 1],
  [0, "is"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "pro-"],
  [1, false],
  [0, "vided"],
  [4, 3],
  [0, "provid-"],
  [1, false],
  [0, "ed"],
  [4, 1],
  [0, "provided"],
  [2, true, 1],
  [0, "by"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [3, 4],
  [0, "us-"],
  [1, false],
  [0, "er"],
  [4, 1],
  [0, "user"],
  [0, "."],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "An-"],
  [1, false],
  [0, "other"],
  [4, 3],
  [0, "Anoth-"],
  [1, false],
  [0, "er"],
  [4, 1],
  [0, "Another"],
  [2, true, 1],
  [3, 4],
  [0, "equal-"],
  [1, false],
  [0, "ly"],
  [4, 1],
  [0, "equally"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "im-"],
  [1, false],
  [0, "portant"],
  [4, 3],
  [0, "impor-"],
  [1, false],
  [0, "tant"],
  [4, 1],
  [0, "important"],
  [2, true, 1],
  [0, "yarn"],
  [2, true, 1],
  [0, "could"],
  [2, true, 1],
  [0, "be"],
  [2, true, 1],
  [0, "a"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "trans-"],
  [1, false],
  [0, "lation"],
  [4, 3],
  [0, "transla-"],
  [1, false],
  [0, "tion"],
  [4, 1],
  [0, "translation"],
  [2, true, 1],
  [0, "which"],
  [2, true, 1],
  [0, "is"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "ex-"],
  [1, false],
  [0, "pected"],
  [4, 3],
  [0, "expect-"],
  [1, false],
  [0, "ed"],
  [4, 1],
  [0, "expected"],
  [2, true, 1],
  [0, "to"],
  [2, true, 1],
  [0, "be"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "po-"],
  [1, false],
  [0, "sitioned"],
  [4, 3],
  [0, "posi-"],
  [1, false],
  [0, "tioned"],
  [4, 1],
  [0, "positioned"],
  [2, true, 1],
  [0, "aside"],
  [2, true, 1],
  [0, "of"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [0, "first"],
  [2, true, 1],
  [0, "yarn"],
  [0, "."],
  [2, true, 1],
  [0, "The"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "fol-"],
  [1, false],
  [0, "lowing"],
  [4, 3],
  [0, "follow-"],
  [1, false],
  [0, "ing"],
  [4, 1],
  [0, "following"],
  [2, true, 1],
  [0, "list"],
  [2, true, 1],
  [0, "shows"],
  [2, true, 1],
  [0, "an"],
  [2, true, 1],
  [0, "non"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "ex-"],
  [1, false],
  [0, "haustive"],
  [4, 3],
  [0, "exhaus-"],
  [1, false],
  [0, "tive"],
  [4, 1],
  [0, "exhaustive"],
  [2, true, 1],
  [0, "list"],
  [2, true, 1],
  [0, "of"],
  [2, true, 1],
  [3, 4],
  [0, "oth-"],
  [1, false],
  [0, "er"],
  [4, 1],
  [0, "other"],
  [2, true, 1],
  [0, "yarns"],
  [2, true, 1],
  [0, "used"],
  [0, ":"],
  [1, true],
  [0, "· "],
  [2, false, 1],
  [0, "Margin"],
  [2, true, 1],
  [0, "notes"],
  [1, true],
  [0, "· "],
  [2, false, 1],
  [3, 4],
  [0, "Com-"],
  [1, false],
  [0, "ments"],
  [4, 1],
  [0, "Comments"],
  [1, true],
  [0, "· "],
  [2, false, 1],
  [3, 9],
  [3, 4],
  [0, "For-"],
  [1, false],
  [0, "mulas"],
  [4, 3],
  [0, "Formu-"],
  [1, false],
  [0, "las"],
  [4, 1],
  [0, "Formulas"],
  [1, true],
  [0, "· "],
  [2, false, 1],
  [3, 4],
  [0, "Fig-"],
  [1, false],
  [0, "ures"],
  [4, 1],
  [0, "Figures"],
  [1, true],
  [0, "· "],
  [2, false, 1],
  [3, 4],
  [0, "Foot-"],
  [1, false],
  [0, "notes"],
  [4, 1],
  [0, "Footnotes"],
  [1, true],
  [0, "A"],
  [2, true, 1],
  [0, "yarn"],
  [2, true, 1],
  [0, "may"],
  [2, true, 1],
  [0, "be"],
  [2, true, 1],
  [3, 4],
  [0, "ei-"],
  [1, false],
  [0, "ther"],
  [4, 1],
  [0, "either"],
  [2, true, 1],
  [0, "parsed"],
  [2, true, 1],
  [0, "from"],
  [2, true, 1],
  [0, "a"],
  [2, true, 1],
  [0, "file"],
  [2, true, 1],
  [0, "or"],
  [2, true, 1],
  [3, 14],
  [3, 4],
  [0, "gener-"],
  [1, false],
  [0, "ated"],
  [4, 8],
  [3, 4],
  [0, "gen-"],
  [1, false],
  [0, "erated"],
  [4, 3],
  [0, "generat-"],
  [1, false],
  [0, "ed"],
  [4, 1],
  [0, "generated"],
  [2, true, 1],
  [0, "while"],
  [2, true, 1],
  [3, 4],
  [0, "pars-"],
  [1, false],
  [0, "ing"],
  [4, 1],
  [0, "parsing"],
  [2, true, 1],
  [3, 4],
  [0, "oth-"],
  [1, false],
  [0, "er"],
  [4, 1],
  [0, "other"],
  [2, true, 1],
  [0, "files"],
  [0, "."],
  [2, true, 1],
  [0, "For"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "ex-"],
  [1, false],
  [0, "ample"],
  [4, 3],
  [0, "exam-"],
  [1, false],
  [0, "ple"],
  [4, 1],
  [0, "example"],
  [0, ":"],
  [2, true, 1],
  [0, "You"],
  [2, true, 1],
  [0, "can"],
  [2, true, 1],
  [0, "choose"],
  [2, true, 1],
  [3, 4],
  [0, "be-"],
  [1, false],
  [0, "tween"],
  [4, 1],
  [0, "between"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "in-"],
  [1, false],
  [0, "cluding"],
  [4, 3],
  [0, "includ-"],
  [1, false],
  [0, "ing"],
  [4, 1],
  [0, "including"],
  [2, true, 1],
  [0, "your"],
  [2, true, 1],
  [0, "margin"],
  [2, true, 1],
  [0, "-"],
  [2, true, 1],
  [0, "notes"],
  [2, true, 1],
  [0, "in"],
  [2, true, 1],
  [0, "your"],
  [2, true, 1],
  [0, "main"],
  [2, true, 1],
  [0, "file"],
  [2, true, 1],
  [0, "("],
  [0, "in"],
  [2, true, 1],
  [0, "this"],
  [2, true, 1],
  [0, "case"],
  [2, true, 1],
  [0, "that"],
  [2, true, 1],
  [0, "file"],
  [2, true, 1],
  [3, 4],
  [0, "in-"],
  [1, false],
  [0, "cludes"],
  [4, 1],
  [0, "includes"],
  [2, true, 1],
  [0, "both"],
  [2, true, 1],
  [0, "yarns"],
  [0, ")"],
  [2, true, 1],
  [0, "and"],
  [2, true, 1],
  [3, 4],
  [0, "stor-"],
  [1, false],
  [0, "ing"],
  [4, 1],
  [0, "storing"],
  [2, true, 1],
  [0, "them"],
  [2, true, 1],
  [0, "in"],
  [2, true, 1],
  [0, "a"],
  [2, true, 1],
  [0, "separate"],
  [2, true, 1],
  [0, "file"],
  [2, true, 1],
  [0, "("],
  [0, "one"],
  [2, true, 1],
  [0, "yarn"],
  [2, true, 1],
  [0, "per"],
  [2, true, 1],
  [0, "file"],
  [0, ")"],
  [0, "."],
  [1, true],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "big"],
  [2, true, 1],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "small"],
  [2, true, 1],
  [0, "The"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "Doc-"],
  [1, false],
  [0, "ument"],
  [4, 3],
  [0, "Docu-"],
  [1, false],
  [0, "ment"],
  [4, 1],
  [0, "Document"],
  [2, true, 1],
  [0, "is"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [3, 4],
  [0, "re-"],
  [1, false],
  [0, "sult"],
  [4, 1],
  [0, "result"],
  [2, true, 1],
  [0, "of"],
  [2, true, 1],
  [3, 4],
  [0, "weav-"],
  [1, false],
  [0, "ing"],
  [4, 1],
  [0, "weaving"],
  [2, true, 1],
  [0, "all"],
  [2, true, 1],
  [0, "Yarns"],
  [2, true, 1],
  [0, "and"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [0, "Woof"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "to-"],
  [1, false],
  [0, "gether"],
  [4, 3],
  [0, "togeth-"],
  [1, false],
  [0, "er"],
  [4, 1],
  [0, "together"],
  [1, true],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "big"],
  [2, true, 1],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "small"],
  [2, true, 1],
  [0, "The"],
  [2, true, 1],
  [0, "Woof"],
  [2, true, 1],
  [0, "holds"],
  [2, true, 1],
  [0, "all"],
  [2, true, 1],
  [0, "Yarns"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "to-"],
  [1, false],
  [0, "gether"],
  [4, 3],
  [0, "togeth-"],
  [1, false],
  [0, "er"],
  [4, 1],
  [0, "together"],
  [2, true, 1],
  [0, "and"],
  [2, true, 1],
  [0, "gives"],
  [2, true, 1],
  [0, "the"],
  [2, true, 1],
  [3, 9],
  [3, 4],
  [0, "Doc-"],
  [1, false],
  [0, "ument"],
  [4, 3],
  [0, "Docu-"],
  [1, false],
  [0, "ment"],
  [4, 1],
  [0, "Document"],
  [2, true, 1],
  [0, "a"],
  [2, true, 1],
  [3, 4],
  [0, "mean-"],
  [1, false],
  [0, "ing"],
  [4, 1],
  [0, "meaning"],
  [0, "."],
  [1, true],
  [0, "unresolved"],
  [2, true, 1],
  [0, "macro"],
  [2, true, 1],
  [0, "big"],
  [1, true]
]);
